- name: "update hostnames"
  hostname:
    name: "{{ inventory_hostname }}"

- name: Check transparent_hugepage exists
  stat:
    path: /sys/kernel/mm/transparent_hugepage
  register: transparent_hugepage_exits

- name: Configure transparent_hugepage/enabled never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
  when: transparent_hugepage_exits.stat.exists

- name: Configure transparent_hugepage/defrag never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
  when: transparent_hugepage_exits.stat.exists

- name: Chenge templates hosts cloud
  template:
    src: hosts.j2
    dest: /etc/cloud/templates/hosts.debian.tmpl

- name: Create hostfiles
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Add an apt key by id from a keyserver
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

- name: Create the /etc/apt/sources.list.d/mongodb-org-4.2.list file for Ubuntu 18.04 (Bionic) 
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: apt-get update
  apt:
    update_cache: yes
    
- name: Install Mongodb
  apt:
    name: mongodb-org